---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The variables file used by the playbooks in the nova group.
# These don't have to be explicitly imported by vars_files: they are autopopulated.

## Service Name
service_name: neutron

# Verbosity Options
debug: False
verbose: True

## only used when the lxc vg is present on the target
container_lvm_fstype: ext4
container_lvm_fssize: 5GB

## General configuration
core_plugin: "{{ neutron_plugins[neutron_plugin_type].plugin_core }}"
interface_driver: neutron.agent.linux.interface.BridgeInterfaceDriver
metering_driver: neutron.services.metering.drivers.iptables.iptables_driver.IptablesMeteringDriver

service_plugins:
  - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
  - neutron.services.loadbalancer.plugin.LoadBalancerPlugin
  - neutron.services.vpn.plugin.VPNDriverPlugin
  - neutron.services.metering.metering_plugin.MeteringPlugin

dhcp_driver: neutron.agent.linux.dhcp.Dnsmasq
neutron_config: /etc/neutron/neutron.conf
neutron_plugin: "/etc/neutron/{{ neutron_plugins[neutron_plugin_type].plugin_ini }}"
neutron_revision: head

## Neutron downtime
neutron_agent_down_time: 120
neutron_report_interval: "{{ neutron_agent_down_time|int / 2 }}"
neutron_agent_polling_interval: 5

## DB
container_mysql_user: neutron
container_mysql_password: "{{ neutron_container_mysql_password }}"
container_database: neutron
neutron_db_max_overflow: 10
neutron_db_pool_size: 120
neutron_db_pool_timeout: 30

## RPC
# ``neutron_rpc_workers`` is an experimental feature in neutron master (as of 03/2015) and
# the value will be 0 by default.
neutron_api_workers: 10
neutron_rpc_workers: 0
rpc_backend: rabbit
neutron_rpc_thread_pool_size: 64
neutron_rpc_conn_pool_size: 30
neutron_rpc_response_timeout: 60

## Nova Auth
service_admin_tenant_name: "service"
service_admin_username: "neutron"
service_admin_password: "{{ neutron_service_password }}"

## Nova User / Group
system_user: neutron
system_group: neutron

## Service Names
service_names: "{{ neutron_services|selectattr('service_en')|map(attribute='service_name')|list }}"

container_directories:
  - { name: "/etc/neutron" }
  - { name: "/etc/neutron/plugins" }
  - { name: "/etc/neutron/plugins/{{ neutron_plugin_type}}" }
  - { name: "/etc/neutron/rootwrap.d" }
  - { name: "/var/cache/neutron" }
  - { name: "/var/lib/neutron", mode: 755 }
  - { name: "/var/lib/neutron/ha_confs" }
  - { name: "/var/lock/neutron" }
  - { name: "/var/log/neutron", mode: 755 }
  - { name: "/var/run/neutron" }

# Neutron Plugins
neutron_plugin_type: ml2

neutron_plugins:
  ml2:
    plugin_core: neutron.plugins.ml2.plugin.Ml2Plugin
    plugin_ini: plugins/ml2/ml2_conf.ini
  plumgrid:
    plugin_core: neutron.plugins.plumgrid.plumgrid_plugin.plumgrid_plugin.NeutronPluginPLUMgridV2
    plugin_ini: plugins/plumgrid/plumgrid.ini

neutron_services:
 - { service_name: neutron-dhcp-agent, service_en: True, service_conf: dhcp_agent.ini, service_rootwrap: rootwrap.d/dhcp.filters }
 - { service_name: neutron-linuxbridge-agent, service_en: True, service_conf: plugins/ml2/ml2_conf.ini, service_rootwrap: rootwrap.d/linuxbridge-plugin.filters }
 - { service_name: neutron-metadata-agent, service_en: True, service_conf: metadata_agent.ini }
 - { service_name: neutron-metering-agent, service_en: True, service_conf: metering_agent.ini }
 - { service_name: neutron-l3-agent, service_en: True, service_conf: l3_agent.ini, service_rootwrap: rootwrap.d/l3.filters }
 - { service_name: neutron-server, service_en: True, service_conf: "{{ neutron_plugins[neutron_plugin_type].plugin_ini }}", service_rootwrap: rootwrap.conf }

## Neutron Quota
neutron_default_quota: -1
neutron_quota_firewall: 1
neutron_quota_firewall_policy: 1
neutron_quota_firewall_rule: 100
neutron_quota_floatingip: 50
neutron_quota_health_monitor: -1
neutron_quota_member: -1
neutron_quota_network: 10
neutron_quota_network_gateway: 5
neutron_quota_packet_filter: 100
neutron_quota_pool: 10
neutron_quota_port: 50
neutron_quota_router: 10
neutron_quota_security_group: 10
neutron_quota_security_group_rule: 100
neutron_quota_subnet: 10
neutron_quota_vip: 10
